### ISSUE TITLE
When there is a pending transaction and the users attempts to send a new transaction, no error message appears

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#213]
**Is your feature request related to a problem? Please describe.**
When there is a pending transaction and the users attempts to send a new transaction, no error message appears. The button just stops working. I am guessing the button is disabled until all pending transactions are done but we should notify the user. 
**Describe the solution you'd like**

<img width="1022" alt="Screen Shot 2020-08-04 at 5 13 24 PM" src="https://user-images.githubusercontent.com/49165468/89345681-d74eba00-d675-11ea-86f3-dfcd9096f6ca.png">

**Comment by markmhx** [comment]
@kyranjamie is going to confirm tis is resolved with general error handling

**Comment by kyranjamie** [comment]
Confirmed that this triggers error state

**Comment by timstackblock** [comment]
This is still broken, error message does not appear the transaction appears to send.

**Comment by timstackblock** [comment]
The error message doesn't seem to trigger. Here is a video of me sending 3 transactions back to back while the first transaction is still pending. 

http://somup.com/cYQrooXs6o

**Comment by kyranjamie** [comment]
Sorry about the back and forward on this one @timstackblock 

![image](https://user-images.githubusercontent.com/1618764/98216547-7fac3d00-1f49-11eb-9c61-fa39e0ecb6d4.png)

I managed to get an error to trigger alright, let me know if this is still an issue and maybe we can jump on a call if so

**Comment by timstackblock** [comment]
Cannot seem to retest this its blocked by these two bugs #322 #321 

<img width="1012" alt="Screen Shot 2020-11-06 at 12 47 47 PM" src="https://user-images.githubusercontent.com/49165468/98398089-5e714c80-202e-11eb-9558-3522104acf1d.png">

**Comment by markmhx** [comment]
@timstackblock it appears the two blocking bugs have been resolved and this can be retested now.

**Comment by markmhx** [comment]
@timstackblock
