### ISSUE TITLE
[4.0.0-beta.3] Bug: Testnet address not accepted by faucet

### ISSUE THREAD

**Issue by omg149** [blockstack/stacks-wallet#259]
Hi receive address of stacks testnet wallet (ubuntu) is not accepted as a valid address by testnet faucet. please see attached screenshots.

![Screenshot 2020-09-25 163231](https://user-images.githubusercontent.com/71886735/94274768-f130ae80-fefa-11ea-8686-b5975407187e.jpg)
![Screenshot 2020-09-25 163539](https://user-images.githubusercontent.com/71886735/94274774-f261db80-fefa-11ea-8627-30a86cdb8640.jpg)

Bug found testing Stacks Wallet build 3e97a15, Thu Sep 24 16:43:38 UTC 2020.

**Comment by markmhx** [comment]
@kyranjamie I assume this is due to an underlying issue with the API and not client-side, given what I'm seeing in Discord?

**Comment by markmhx** [comment]
@omg149 I suggest trying the faucet again since we also had to update the faucet webpage post-release of Argon, and that update may have happened _after_ you attempted to get some STX.

**Comment by kyranjamie** [comment]
This is fixed.

**Comment by markmhx** [comment]
I'm still getting a 500 with the faucet. @kyranjamie should we close, however, given that it appears server-side?

<img width="1564" alt="Screen Shot 2020-10-07 at 15 14 28" src="https://user-images.githubusercontent.com/28991/95335604-e6d5c380-08af-11eb-8c22-5d49ac2fc20d.png">

**Comment by kyranjamie** [comment]
Can do, or move to another repo. The issue isn't to do with the wallet's address generation.

**Comment by diwakergupta** [comment]
> I'm still getting a 500 with the faucet. @kyranjamie should we close, however, given that it appears server-side?

@markmhx is there a corresponding issue on stacks-blockchain-api for this? Independently, I do think we should tweak the warning the wallet shows: a user would be very confused if the issue is with the faucet API but we tell her the STX address is invalid.

**Comment by markmhx** [comment]
@diwakergupta Good call on tracking those as well. I've created issues in the API repo with https://github.com/blockstack/stacks-blockchain-api/issues/278 and in the blockstack.org one with https://github.com/blockstack/blockstack.org/issues/1167
