### ISSUE TITLE
Next duration starts in 5 hours never updates

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#434]

**Comment by markmhx** [comment]
@timstackblock It also indicated for me 5 hours for a single cycle yesterday upon initiation, yet it's still only partially complete today. Did you see this resolved in a newer build?

![image](https://user-images.githubusercontent.com/28991/103307988-af3f6900-4a11-11eb-9a13-1866b5c782c8.png)

**Comment by timstackblock** [comment]
No its still an issue but I closed it because I was going to wait for @lgalabru stacking PR to retest the functionality thought it might be related. Either way we should keep it open and close it afterwards if it is resolved.
